### ISSUE TITLE
Can you upload to NPM like `ghost-s3-storage` did?

### ISSUE THREAD

**Issue by legendtang** [minwe/qn-store#1]
https://www.npmjs.com/package/ghost-s3-storage

```
'use strict';
module.exports = require('ghost-s3-storage');
```

So we can use the storage API like this.

**Comment by minwe** [comment]
https://www.npmjs.com/package/ghost-qn-store

**Comment by legendtang** [comment]
Since you have require extra modules like "fs-extra", "bluebird" & "moment" which are not accessible in the current directory, I suggest those missing package be included in the dependencies so that this NPM package would be truly working without modified `package.json` in the main project.

**Comment by minwe** [comment]
It's not caused by `bluebird`, `moment`, .etc. It's caused by wrong path of requiring ghost utils, fixed in https://github.com/minwe/qn-store/releases/tag/v0.0.2, try to install the new version from npm.

**Comment by sanddudu** [comment]
Ghost utils are not actually required by all storage modules.

I deleted it in my code, and it works well.

https://github.com/sanddudu/upyun-ghost-store/blob/master/index.js

**Comment by minwe** [comment]
I use Ghost utils to transform Chinese characters in filename. 

https://github.com/minwe/qn-store/blob/675da6f829275a5d610f750bc2dc2a2eee125295/index.js#L52

There are many ways to rename filename, I'd like to make readable filename and friendly URL on the storage server.

**Comment by legendtang** [comment]
Apparently, if you using this method,

```
'use strict';

module.exports = require('ghost-qn-store');
```

the `bluebird` and `moment` is still in need.

Additionally, the utils path of your NPM version is broken, which should have been `../ghost/core/server/utils`. You should re-update your NPM package according to https://github.com/legendtang/qn-store/commit/2523f80af078ef8e882ea43f75be097cf5238b24 so that your package is usable.

**Comment by minwe** [comment]
That is your situation.

I use it like this:
- Create `content/storage/qn-store/index.js` and add below code to the file:
  
  ``` js
  'use strict';
  
  module.exports = require('ghost-qn-store');
  
  ```
- Run `npm i  ghost-qn-store --save` on Ghost root dir.

`bluebird`, `moment` are the official dependencies of Ghost, so I ignore them.

It works well for me.

I think your directory structure is not like mine, so it not works. 

You can create your own version on the way what you want.

**Comment by legendtang** [comment]
Alright, I will upload another NPM package.
