### ISSUE TITLE
路径问题

### ISSUE THREAD

**Issue by MeowCold** [minwe/qn-store#10]
你好现在发现一旦使用fileKey就会出现md5值后面带着文件名 如何才能做到有年月和SHA1或MD5 而不会带着文件名
我现在知道可以指定为 默认 即不带prefix: 'YYYY/MM/' 是七牛默认sha1做文件名
而带prefix: 'YYYY/MM/' 则为2016/09/文件名 
而我现在想要YYYY/MM/MD5 不知道该怎么做主要是为了去重名和一图多种样式

**Comment by minwe** [comment]
https://support.qiniu.com/hc/kb/article/112817/

如果只是为了去重名的话 prefix: 'YYYY/MM/' 没有必要，七牛的 hash 算法不会出现相同的 key 的，除非你是同一个文件上传多次。

**Comment by MeowCold** [comment]
额 我主要是为了好找单张出问题的图所以划分年月 233 
暂时不会添加这种需求吗？

**Comment by minwe** [comment]
现在的 hash 是从七牛返回来的，如果要加上前缀的话等于是要自己算好 hash，然后加上自定义的前缀作为存储 key 传到七牛，我回头看一下怎么处理。

**Comment by MeowCold** [comment]
谢谢 抱歉麻烦你了

**Comment by minwe** [comment]
加上了 `hashAsBasename` 这个选项，你可以试一下：

``` javascript
fileKey: {
        hashAsBasename: true,
        prefix: function() {
            return 'YYYY/MM/';
        }
}
```
