### ISSUE TITLE
qn-store 同步到七牛时，文件路径处理有问题。

### ISSUE THREAD

**Issue by yujiangshui** [minwe/qn-store#2]
在文章中上传图片，qn-store 拿到的 url 是：

`http://7xoy6u.com1.z0.glb.clouddn.com%20/2016/01/qq20160108-2-2x-1452232107229.png`

但是七牛网站上图片地址是：

`http://7xoy6u.com1.z0.glb.clouddn.com/2016%2F01%2Fqq20160108-2-2x-1452232116469.png`

上面那个 Ghost 拿到的地址有问题，结果导致图片路径找不到从而无法插入到文章里面。

**Comment by minwe** [comment]
我自己在使用七牛，没遇到这个问题

`config.js` 设置：

``` js
{
  // ...
  domain: 'https://dn-csspod.qbox.me',
  filePath: '[images]/YYYY/MM/'
  // ...
}
```

上传文件名为 `屏幕快照-2016-01-08-上午11.27.28.jpg` 的图片，
返回的地址是：

```
https://dn-csspod.qbox.me/images/2016/01/ping-mu-kuai-zhao-2016-01-08-shang-wu-11-27-28-1452239284911.jpg
```

没问题。

**Comment by yujiangshui** [comment]
我看了下应该是七牛那边 SDK 出的问题，返回回来的 url 域名跟地址多了个空格。

![image](https://cloud.githubusercontent.com/assets/2942913/12199465/4a8604e4-b653-11e5-80d2-1c77b7ff1964.png)

**Comment by yujiangshui** [comment]
排查了下，原来是复制七牛地址的时候，复制上了一个空格。。。close
