### ISSUE TITLE
你好，我这边用docker搭建的ghost 1,2版本好像用不了

### ISSUE THREAD

**Issue by lracker** [minwe/qn-store#20]
我也按照了上面的说明设置了一遍，结果还是上传到服务器上而不是上传到七牛云。不知道是最新的ghost不兼容还是什么问题。http://p3w1i4b42.bkt.clouddn.com/111.png
希望能帮忙看一下，谢谢！

**Comment by minwe** [comment]
配置文件名字对吗？生产环境文件名用 `config.production.json`

**Comment by lracker** [comment]
就是在config.production.json里改的，但我试了几次也按照上面的配置弄，还是不行，，，

**Comment by minwe** [comment]
那你在`config.development.json` 里面也加上试试

**Comment by lracker** [comment]
好了！谢谢大佬，发现是一些标点细节的问题
