### ISSUE TITLE
每次上传文件的时候都会上传两份大小不一，内容相同的文件

### ISSUE THREAD

**Issue by HuColin** [minwe/qn-store#26]
![image](https://user-images.githubusercontent.com/16102181/56860611-06827000-69cb-11e9-8408-cfdfed82b2df.png)
每次上传的图片在七牛的后台都可以看到是储存了两份的，其中有一份文件比较小感觉像是被压缩过了一样，请问一下这个怎样才能只保留一份文件呢？
我的配置如下：
```json
{
···
    "uploadURL": "up-z2.qiniup.com",
    "fileKey": {
      // use Qiniu hash as file basename, if set, `safeString` will be ignored
      "hashAsBasename": false,
      "safeString": true,
      "prefix": "YYYY/MM/DD/",
      "suffix": "-Ghost", 
      "extname": "true"
    }
···
}
```
PS: README.md中关于uploadURL中的描述可能需要修改
[Qiniu储存区域](https://developer.qiniu.com/kodo/manual/1671/region-endpoint)
```
    // if your app outside of China, please set `uploadURL` to `http://up.qiniug.com/`
    // uploadURL: 'http://up.qiniu.com/'
```

**Comment by j4tmr** [comment]
是的，+1

**Comment by minwe** [comment]
@HuColin 

`"suffix": "-Ghost",  ` 改成下划线试试？

**Comment by j4tmr** [comment]
@minwe 不是这个suffix的问题，比如我生成了两个大小不一的文件，一个文件名是“202004/59bf-isuiksp0182731_Ghost.jpg”，另一个是“202004/59bf-isuiksp0182731_o_Ghost.jpg”，会有一个_o后缀的更大的文件和一个原文件名的更小的文件

**Comment by minwe** [comment]
@jhd4tmr 咨询一下七牛的客服，看看是不是他们默认启用了压缩机制，文档里没有找到压缩这个参数。

**Comment by minwe** [comment]
@jhd4tmr 是不是七牛后台配置过水印设置什么的？

**Comment by j4tmr** [comment]
@minwe 是ghost自己的问题，新版本ghost，本地存储图片的时候也会存两个文件，一个压缩过尺寸大小等用来适应页面显示，另一个源文件。https://ghost.org/docs/concepts/config/#image-optimisation 关闭这个的话能只保留源文件，但仁者见仁吧。

**Comment by minwe** [comment]
Image optimisation
When uploading images into the Ghost editor, they are automatically processed and compressed by default. This can be disabled in your config.[env].json file using:

```
"imageOptimization": {
  "resize": false
}
```
Image compression details:

Resize the image to 2000px max width
JPEG's are compressed to 80% quality.
Meta data removed
The original image is kept with the suffix _o.


@HuColin https://ghost.org/docs/concepts/config/#image-optimisation 可以参考这个配置一下。

**Comment by HuColin** [comment]
@minwe 非常感谢，问题解决了
