### ISSUE TITLE
You are missing dependencies in your adapter content/adapters/storage/qn-store

### ISSUE THREAD

**Issue by ghost** [minwe/qn-store#27]
ghost 3.25 版本路径改了
const config = require(path.join(ghostRoot, 'core/shared/config'));
const errors = require('@tryghost/errors');

**Comment by halfrost** [comment]
> ghost 3.25 版本路径改了
> const config = require(path.join(ghostRoot, 'core/shared/config'));
> const errors = require('@tryghost/errors');

我也遇到这个错误了。@gaofeng03

**Comment by halfrost** [comment]
具体的改动在这里 PR 这里：https://github.com/TryGhost/Ghost/pull/11850

**Comment by halfrost** [comment]
好像只改动这 2 行还是不行？？@gaofeng03

```
const config = require(path.join(ghostRoot, 'core/shared/config'));
const errors = require('@tryghost/errors');
```

改完以后我还是报错：

```
Message: Unable to find storage adapter qn-store in ,/var/www/ghost/content/adapters/,/var/www/ghost/versions/3.25.0/core/server/adapters/.
```
看这个报错信息说的是 qn-store 没有识别出来是 storage adapte，这两个路径下我已经都放了 qn-store.

**Comment by gaofeng03** [comment]
这个报错好像不是引用的问题

**Comment by ghost** [comment]
> 好像只改动这 2 行还是不行？？@gaofeng03
> 
> ```
> const config = require(path.join(ghostRoot, 'core/shared/config'));
> const errors = require('@tryghost/errors');
> ```
> 
> 改完以后我还是报错：
> 
> ```
> Message: Unable to find storage adapter qn-store in ,/var/www/ghost/content/adapters/,/var/www/ghost/versions/3.25.0/core/server/adapters/.
> ```
> 
> 看这个报错信息说的是 qn-store 没有识别出来是 storage adapte，这两个路径下我已经都放了 qn-store.

这个报错好像不是引用的问题，检查下配置文件里面路径是否正确 @halfrost

**Comment by halfrost** [comment]
> > 好像只改动这 2 行还是不行？？@gaofeng03
> > ```
> > const config = require(path.join(ghostRoot, 'core/shared/config'));
> > const errors = require('@tryghost/errors');
> > ```
> > 
> > 
> > 改完以后我还是报错：
> > ```
> > Message: Unable to find storage adapter qn-store in ,/var/www/ghost/content/adapters/,/var/www/ghost/versions/3.25.0/core/server/adapters/.
> > ```
> > 
> > 
> > 看这个报错信息说的是 qn-store 没有识别出来是 storage adapte，这两个路径下我已经都放了 qn-store.
> 
> 这个报错好像不是引用的问题，检查下配置文件里面路径是否正确 @halfrost

我的配置文件一直没有改动呢。。我的配置是这样的:

```
"storage": {
    "active": "qn-store",
    "qn-store": {
      "accessKey": "XXXXXXXX",
      "secretKey": "XXXXXXXXX",
      "bucket": "XXXXXXXX",
      "origin": "XXXXXXXXXX",
      "fileKey": {
        "safeString": true,
        "prefix": "[Blog/]",
        "suffix": "",
        "extname": true
      }
    }
  },
```
然后 qn-store 在 /var/www/ghost/content/adapters/storage/qn-store 这个路径下。@gaofeng03

**Comment by ghost** [comment]
> > > 好像只改动这 2 行还是不行？？@gaofeng03
> > > ```
> > > const config = require(path.join(ghostRoot, 'core/shared/config'));
> > > const errors = require('@tryghost/errors');
> > > ```
> > > 
> > > 
> > > 改完以后我还是报错：
> > > ```
> > > Message: Unable to find storage adapter qn-store in ,/var/www/ghost/content/adapters/,/var/www/ghost/versions/3.25.0/core/server/adapters/.
> > > ```
> > > 
> > > 
> > > 看这个报错信息说的是 qn-store 没有识别出来是 storage adapte，这两个路径下我已经都放了 qn-store.
> > 
> > 
> > 这个报错好像不是引用的问题，检查下配置文件里面路径是否正确 @halfrost
> 
> 我的配置文件一直没有改动呢。。我的配置是这样的:
> 
> ```
> "storage": {
>     "active": "qn-store",
>     "qn-store": {
>       "accessKey": "XXXXXXXX",
>       "secretKey": "XXXXXXXXX",
>       "bucket": "XXXXXXXX",
>       "origin": "XXXXXXXXXX",
>       "fileKey": {
>         "safeString": true,
>         "prefix": "[Blog/]",
>         "suffix": "",
>         "extname": true
>       }
>     }
>   },
> ```
> 
> 然后 qn-store 在 /var/www/ghost/content/adapters/storage/qn-store 这个路径下。@gaofeng03

@halfrost contentPath 是否设置了？
"paths": {
    "contentPath": "/usr/ghost-local/content"
  }

**Comment by halfrost** [comment]
@gaofeng03 contentPath 一直都有设置，也都没有改过：

```
  "paths": {
    "contentPath": "/var/www/ghost/content"
  }
```

**Comment by halfrost** [comment]
@gaofeng03 你的博客现在能用 qn-store 么？我看你的博客好像不报错了。你是怎么修复这个 issue 的错误的呢？你的配置是？

**Comment by ghost** [comment]
> @gaofeng03 你的博客现在能用 qn-store 么？我看你的博客好像不报错了。你是怎么修复这个 issue 的错误的呢？你的配置是？
这是我的配置 @halfrost
"storage": {
    "active": "qn-store",
    "qn-store": {
    }
},
"paths": {
    "contentPath": "/usr/ghost-local/content"
},

**Comment by halfrost** [comment]
> > @gaofeng03 你的博客现在能用 qn-store 么？我看你的博客好像不报错了。你是怎么修复这个 issue 的错误的呢？你的配置是？
> > 这是我的配置 @halfrost
> > "storage": {
> > "active": "qn-store",
> > "qn-store": {
> > }
> > },
> > "paths": {
> > "contentPath": "/usr/ghost-local/content"
> > },

你这个配置没有报错么？你只改了上面说的那 2 个路径，就没问题了，是么？

**Comment by ghost** [comment]
> > > @gaofeng03 你的博客现在能用 qn-store 么？我看你的博客好像不报错了。你是怎么修复这个 issue 的错误的呢？你的配置是？
> > > 这是我的配置 @halfrost
> > > "storage": {
> > > "active": "qn-store",
> > > "qn-store": {
> > > }
> > > },
> > > "paths": {
> > > "contentPath": "/usr/ghost-local/content"
> > > },
> 
> 你这个配置没有报错么？你只改了上面说的那 2 个路径，就没问题了，是么？

是的，你这个应该是别的问题

**Comment by halfrost** [comment]
@gaofeng03 那你的这些参数是什么呢？我想核对核对。

```
    OS: CentOS Linux, v7
    Node Version: v12.18.2
    Ghost Version: 3.26.1
    Ghost-CLI Version: 1.14.1
```

**Comment by ghost** [comment]
> @gaofeng03 那你的这些参数是什么呢？我想核对核对。
> 
> ```
>     OS: CentOS Linux, v7
>     Node Version: v12.18.2
>     Ghost Version: 3.26.1
>     Ghost-CLI Version: 1.14.1
> ```

OS: centos 7
Node: v10.14.1
Ghost Version: 3.25.0
Ghost-CLI version: 1.14.1

**Comment by halfrost** [comment]
好吧，那配置差不多。那我自己再找找原因吧。看看是啥其他的问题，谢谢大佬回复~ @gaofeng03

**Comment by minwe** [comment]
5.0.0 已经修复
