### ISSUE TITLE
Please correct the install instructions

### ISSUE THREAD

**Issue by ErisDS** [minwe/qn-store#6]
Hi there!

I have just done a review of all the modules that have been linked [here](https://github.com/TryGhost/Ghost/wiki/Using-a-custom-storage-module).

Your install instructions require users to do an `npm install --save` - this modifies the package.json and makes the upgrade path for Ghost much, much harder. This was never the intention with the storage system. 

Instead of `npm install --save`, please update your README and advise people to do the following:

`mkdir content/storage` (make the storage folder if it doesn't exist yet)
`cp node_modules/<module_name> content/storage/<module_name>` (copy the module into the right location)

That makes it much easier to upgrade Ghost in future. 

We are in the process of adding a cli tool that will do these steps automatically, so if your module isn't setup to work this way, it will need to be very soon 😉

**Comment by minwe** [comment]
Hi,

The install instruction is updated. 

I think it is not friendly enough to normal user. it would be better if Ghost can install modules witch set in `config.js` automatically.

**Comment by ErisDS** [comment]
Hi @minwe thanks for updating these so quickly.

The storage module system, just like installing Ghost itself, is not really designed for people who aren't developers. Still, I think it's more "friendly" to have a couple of extra install steps that you have to run one time, than having a setup that will inexplicably disappear every time you run an update.

As I mentioned, we're working on a cli tool that will do these steps automatically, as well as starting to look at upgrade tooling. This should make it a lot easier, but makes it even more important that install instructions on these repos match how the tool will work, else we'll run into issues with people using the new tooling.

**Comment by minwe** [comment]
@ErisDS 

You are wright. 

Thanks for your team's hard working on Ghost.

**Comment by ErisDS** [comment]
😊  Thanks for supporting our community!

(closing as this is done)
