### ISSUE TITLE
Breaking changes in Ghost 0.10.0

### ISSUE THREAD

**Issue by kirrg001** [minwe/qn-store#7]
Hey!

We will soon release Ghost `0.10.0` - in about 2 days.
It contains breaking changes for the storage adapter, see https://github.com/TryGhost/Ghost/wiki/Using-a-custom-storage-module.

**Comment by minwe** [comment]
I'll see the breaking detail and update this module later.

Thanks.

**Comment by tkizm1** [comment]
still no fix yet

**Comment by minwe** [comment]
Fixed in a1d4831fdbe06aa4bf894d17a09e305f72e598bd.
