### ISSUE TITLE
qn-store 路径问题

### ISSUE THREAD

**Issue by MeowCold** [minwe/qn-store#8]
如何指定路径为 http：//XXXXX.XXXX.com/2016/04/MD5.jpg
如何设置md5配置

**Comment by minwe** [comment]
不设置 'fileKey' 参数就会使用七牛默认的 hash 算法生成key，没有扩展名

返回的文件路径类似 `http://qtestbucket.qiniudn.com/FvnDEnGu6pjzxxxc5d6IlNMrbDnH`。

**Comment by MeowCold** [comment]
谢谢之前有点误读

**Comment by MeowCold** [comment]
你好现在发现一旦使用fileKey就会出现md5值后面带着文件名 如何才能做到有年月和SHA1或MD5 而不会带着文件名
